name: 'upload'
on: # rebuild any PRs and main branch changes
  pull_request:
    branches:
      - main
    paths:
      - 'src/al/dummy.txt'
  push:
    branches:
      - main
      - 'releases/*'
    paths:
      - 'src/al/dummy.txt'

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          milliseconds: 1000
        id: wait
      - run: |
          echo "Hello, cj!"
          echo "${{steps.wait.outputs.time}}"
